name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Prepare NSIS
      #   if: matrix.os == 'windows-latest'
      #   id: prep_nsis
      #   uses: joncloud/makensis-action@v1
      #   with:
      #     just-include: true

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: yarn version
        run: |
          yarn version
      - name: node version
        run: |
          node --version
      # - name: Build App [macOS]
      #   if: matrix.os == 'macOS-latest'
      #   run: |
      #     yarn
      #     npm install
      #     yarn gulp dist
      - name: Build App [ubuntu]
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm install
          npm run dist:zip
      # - name: Build App [windows]
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     yarn
      #     npm install
      #     yarn gulp dist --platforms=win32
      #     yarn gulp dist --platforms=win64
      #   env:
      #     NSIS_PATH: ${{ steps.prep_nsis.outputs.nsis-path }}

      - name: set version
          run: echo "VERSION=$(npm pkg get version | tr -d '\"')" >> $VERSION

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: dist/upscayl${{env.VERSION}}.zip

